schema_version: 1

context:
  version: "2.1.0"

package:
  name: mcp-types
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mcp-types/mcp_types-${{ version }}.tar.gz
  sha256: 16f91064ce33d7ee7a75a7e198a437172215180c16d4bbcfa0e61488ede92c54

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - uv-dynamic-versioning
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.12.0
    - typing_extensions >=4.13.0

tests:
  - python:
      imports:
        - mcp_types
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Model Context Protocol wire types
  license: MIT
  license_file: LICENSE
  homepage: https://modelcontextprotocol.io
  documentation: https://py.sdk.modelcontextprotocol.io/

extra:
  recipe-maintainers:
    - jan-janssen
